services:
  - type: web
    name: tella-grupo09
    env: python
    rootDir: Tella_TurismoNacional/tella_project
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn tella_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SETTINGS_MODULE
        value: tella_project.settings
      - key: DEBUG
        value: "0"
